name: Docker Build and Push Unity Catalog UI Image

on:
  push:
    branches:
      - 'build'

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest
    environment: build
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push Unity Catalog UI Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ./unity/ui/
          tags: vinayramg/unitycatalog-ui_v0.2.1:latest
          platforms: linux/amd64, linux/arm64, linux/x86_64   # Multi-platform support
          cache-from: type=registry,ref=vinayramg/unitycatalog-ui_v0.2.1:cache
          cache-to: type=inline,mode=max
      